package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 */
@WebService(name = "ServiceHttpGet", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceHttpGet {

    /**
     * @param identity
     * @param request
     * @param filter
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "ABESubmit")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String abeSubmit(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "identity") String identity,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "request") String request,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "filter") String filter);

    /**
     * @param abeConnectionString
     * @param userName
     * @param password
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "CreateSession")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String createSession(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ABEConnectionString") String abeConnectionString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserName") String userName,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password") String password);

    /**
     * @param passportID
     * @param userName
     * @param password
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "ClearSession")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String clearSession(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "PassportID") String passportID,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserName") String userName,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password") String password);

    /**
     * @param identity
     * @param request
     * @param filter
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "ABE_SendCommand_1_2")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String abeSendCommand12(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "identity") String identity,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "request") String request,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "filter") String filter);

}
